name: Cargo Build

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust MOC gui - latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Toolchain update
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

    - name: Toolchain info
      run: cargo --version --verbose
      run: rustc --version
      run: cargo clippy --version

    - name: Build
      run: cargo build --verbose
      run: trunk build

    - name: Run tests
      run: cargo test --verbose