name: Cargo Build

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust MOC gui - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - uses: actions/checkout@v3

    - name: Toolchain update
      run: |
        rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        sudo apt-get install librust-atk-dev
        sudo apt-get install libgtk-3-dev
    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version

    - name: Build
      run: |
        cargo build --verbose
        trunk build

    - name: Run tests
      run: cargo test --verbose